databaseUri: BOTTEN_NAPPET_DATABASE_URI
loggingFile: BOTTEN_NAPPET_LOG_FILE
loggingLevel: BOTTEN_NAPPET_LOGGING_LEVEL
twitchAppClientId: TWITCH_APP_CLIENT_ID
twitchAppClientSecret: TWITCH_APP_CLIENT_SECRET
twitchAppOAuthRedirectUrl: TWITCH_APP_OAUTH_REDIRECT_URL
twitchUserName: TWITCH_USER_NAME
