backend:
  shared:
    databaseUri: BOTTEN_NAPPET_SHARED_DATABASE_URI
  twitch:
    databaseUri: BOTTEN_NAPPET_TWITCH_DATABASE_URI
    appClientId: TWITCH_APP_CLIENT_ID
    appClientSecret: TWITCH_APP_CLIENT_SECRET
    appOAuthRedirectUrl: TWITCH_APP_OAUTH_REDIRECT_URL
    userName: TWITCH_USER_NAME
  vidy:
      rootUrl: VIDY_API_ROOT_URL
      videoLinkBaseUrl: VIDY_VIDEO_LINK_BASE_URL
      keyId: VIDY_API_KEY_ID
      keySecret: VIDY_API_KEY_SECRET
      systemUuid: VIDY_SYSTEM_UUID
frontend:
    port: PORT
shared:
  logging:
    file: BOTTEN_NAPPET_SHARED_LOG_FILE
    level: BOTTEN_NAPPET_SHARED_LOGGING_LEVEL
  zmq:
    keys:
      server:
        private: BOTTEN_NAPPET_SHARED_ZMQ_SERVER_PRIVATE_KEY
        public: BOTTEN_NAPPET_SHARED_ZMQ_SERVER_PUBLIC_KEY
      client:
        private: BOTTEN_NAPPET_SHARED_ZMQ_CLIENT_PRIVATE_KEY
        public: BOTTEN_NAPPET_SHARED_ZMQ_CLIENT_PUBLIC_KEY
    address:
      xpublisher: BOTTEN_NAPPET_SHARED_ZMQ_PUBLISHER_ADDRESS
      xsubscriber: BOTTEN_NAPPET_SHARED_ZMQ_SUBSCRIBER_ADDRESS
graphs:
    enabled: BOTTEN_NAPPET_GENERATE_GRAPH
