backend:
  databaseUri: BOTTEN_NAPPET_BACKEND_DATABASE_URI
  twitch:
    appClientId: TWITCH_APP_CLIENT_ID
    appClientSecret: TWITCH_APP_CLIENT_SECRET
    appOAuthRedirectUrl: TWITCH_APP_OAUTH_REDIRECT_URL
    userName: TWITCH_USER_NAME
frontend:
    port: PORT
shared:
  logging:
    file: BOTTEN_NAPPET_SHARED_LOG_FILE
    level: BOTTEN_NAPPET_SHARED_LOGGING_LEVEL
  zmqAddress: BOTTEN_NAPPET_SHARED_ZMQ_ADDRESS
