backend:
    pollingInterval:
        default: 30000
        streaming: 30000
        cheermotes: 600000
    databaseUri: null
    followingPollingLimit: 5
    logging:
        file: null
        level: error
    topic:
        twitch:
            incomingIrcCommand: "external:backend:twitch:incoming:irc:command"
            outgoingIrcCommand: "external:backend:twitch:outgoing:irc:command"
            incomingPubSubEvent: "external:backend:twitch:incoming:pubsub:event"
    twitch:
        appClientId: null
        appClientSecret: null
        appOAuthRedirectUrl: null
        appScopes:
            - channel_feed_read
        appTokenRefreshInterval: 2700000
        ircWebSocketUri: "wss://irc-ws.chat.twitch.tv:443/"
        oauthAuthorizationUri: "https://api.twitch.tv/kraken/oauth2/authorize"
        oauthTokenRevocationUri: "https://api.twitch.tv/kraken/oauth2/revoke"
        oauthTokenUri: "https://api.twitch.tv/kraken/oauth2/token"
        oauthTokenVerificationUri: "https://api.twitch.tv/kraken"
        pubSubWebSocketUri: "wss://pubsub-edge.twitch.tv/"
        userName: null
        usersDataUri: "https://api.twitch.tv/helix/users"
    vidy:
        rootUrl: null
        videoLinkBaseUrl: null
        keyId: null
        keySecret: null
        systemUuid: null
frontend:
    port: 3000
    static:
        publicRootDirectory: "./src/frontend/public"
shared:
    applicationName: botten-nappet
    logging:
        file: null
        level: error
    topic:
        twitch:
            incomingCheeringEvent: "internal:shared:twitch:incoming:cheering:event"
            incomingWhisperEvent: "internal:shared:twitch:incoming:whisper:event"
            incomingCheeringWithCheermotesEvent: "internal:shared:twitch:incoming:cheering:with:cheermotes:event"
            incomingCheermotesEvent: "internal:shared:twitch:incoming:cheermotes:event"
            incomingFollowingEvent: "internal:shared:twitch:incoming:following:event"
            incomingStreamingEvent: "internal:shared:twitch:incoming:streaming:event"
            incomingSubscriptionEvent: "internal:shared:twitch:incoming:subscription:event"
        vidy:
            incomingSearchResultEvent: "external:shared:vidy:incoming:search:result:event"
            outgoingSearchCommand: "external:shared:vidy:outgoing:search:command"
    zmqAddress: "tcp://127.0.0.1:54859"
